config/routes.rb
Rails.application.routes.draw do
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :notes
  resources :users
  resources :reservations
  resources :planets 
  resources :reviews

end

app/models/ahoy/event.rb
class Ahoy::Event < ApplicationRecord
  include Ahoy::QueryMethods

  self.table_name = "ahoy_events"

  belongs_to :visit
  belongs_to :user, optional: true

  serialize :properties, JSON
end

app/models/ahoy/visit.rb
class Ahoy::Visit < ApplicationRecord
  self.table_name = "ahoy_visits"

  has_many :events, class_name: "Ahoy::Event"
  belongs_to :user, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user

    

end

app/models/planet.rb
class Planet < ApplicationRecord
    has_many :reservations
    has_many :users, through: :reservations
    has_many :reviews

    def my_reviews
        self.reviews.select do |review|
            review.planet.id = self.id  
        end 
    end 
end 

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :user 
    belongs_to :planet    

    
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :planet
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reservations
    has_many :planets, through: :reservations
    has_many :reviews
    has_many :notes

    has_secure_password
    has_many :visits, class_name: "Ahoy::Visit"


    # validates :username, presence: true, uniqueness: true
    

    def my_reviews
        self.reviews.select do |review|
            review.user.id = self.id  
        end 
    end 

    def my_first_review
        my_reviews.first
    end

    def my_last_review
        my_reviews.last
    end


    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    after_action :track_action


    
    
    def current_user
        user_id = session[:user_id]
        user_id && User.find(user_id)
    end
    
    def authenticate!
        unless current_user
            flash[:info] = "**Need to be logged for this function**"
            redirect_to planets_path
        end
    end
    
    protected
  
    def track_action
    ahoy.track "Ran action", request.path_parameters
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

    def index 
        @notes = Note.all
    end

    def show
        @note = Note.find(params[:id])
    end

    def new
        @note = Note.new
    end
    
    def create
        @note = Note.new(note_params)
        @note.user_id = session[:user_id]
        if @note.save
            redirect_to note_path(@note)
        else
            render :new
        end
    end

    def edit
        @note = Note.find(params[:id])
    end

    def update
        @note = Note.find(params[:id])
        @note.user_id = session[:user_id]
        if @note.update(note_params)
            redirect_to note_path(@note)
        else
            render :new
        end
    end

    def destroy
        @note = Note.find(params[:id])
        if @note.user_id = session[:user_id]
            @note.destroy
        else
            flash[:info] = "You can only delete your own notes."
        end
        redirect_to notes_path
    end

    private

    def note_params
        params.require(:note).permit(:id, :user_id, :blog, :img_url, :title)
    end

    

end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController

    def index 
        @planets = Planet.all
    end

    def show
        @planet = Planet.find(params[:id])
         @reviews = @planet.my_reviews
    end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

    def index 
        @reservations = Reservation.all 
        
    end

    def show
        @reservation = Reservation.find(params[:id])
    end

    def new
        @reservation = Reservation.new
    end

    def create
        @reservation = Reservation.new(reservation_params)
        @reservation.user_id = session[:user_id]
        if @reservation.save
            redirect_to reservation_path(@reservation)
        else
            render :new
        end
    end

    def destroy
        @reservation = Reservation.find(params[:id])
        if @reservation.user == current_user
            @reservation.destroy
        else
            flash[:info] = "You are not allowed to delete other peoples reservations."
        end
        redirect_to reservations_path
    end

    private 

    def reservation_params 
        params.require(:reservation).permit(:user_id, :planet_id, :date_time, :cost)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate!, except: [:index, :show]

    def index 
        @reviews = Review.all
    end 

    def show 
        @review = Review.find(params[:id])
    end 

    def new
        @review = Review.new
    end 

    def create 
        @review = Review.new(review_params)
        @review.user_id = current_user.id
        if @review.save 
            redirect_to review_path(@review.id)
        else 
            render :new
        end 
    end 

    def edit 
        @review = Review.find(params[:id])
        render :edit 
    end 
    
      def update
        @reivew = Review.find(params[:id])
        @review.update(review_params)
        redirect_to review_path(@review.id)
      end
    
      def destroy
        @review = Review.find(params[:id])
        if @review.user == current_user
          @review.destroy
        else
          flash[:info] = "You can only delete your own reviews"
        end
        redirect_to reviews_path
      end



    private

    def review_params
        params.require(:review).permit(:user_id, :planet_id, :img_url, :rating, :title, :planet_review)
    end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new 
        @user = User.new
    end

    def create 
        @user = User.find_by(username: params[:username])
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id 
            flash[:info] = "You are logged in"
            redirect_to user_path(@user)
        else
            @error = "No such username or wrong email"
            render :new 
        end 
        ahoy.authenticate(@user)

    end 

    def destroy
        session[:user_id] = nil
        redirect_to planets_path
    end 


end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authenticate!, except: [:new, :create]


    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
        @reviews = @user.my_reviews
    end 

    def new
        @user = User.new
    end 

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id 
            flash[:info] = "You are logged in"
            redirect_to user_path(@user)
        else
            render :new
        end 
    end 

    def edit 
        @user = User.find(params[:id])
        render :edit 
    end 

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to planets_path
    end 
    

    private 

    def user_params
        params.require(:user).permit(:name, :bio, :age, :img_url, :username, :password)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backpacks_helper.rb
module BackpacksHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/notes/_form.html.erb
<%= form_for @note do |f| %>
    Title: <%= f.text_field :title %><br />
    Notes: <%= f.text_area :blog %><br />
    IMG url : <%= f.text_field :img_url %><br />
<%= f.submit %>
<% end %>

app/views/notes/edit.html.erb
<h1>Edit this note</h1>

<%=render ("form")%>

app/views/notes/index.html.erb
<div class="split left">
  <div class="centered">
    <img src="https://us.moleskine.com/ccstore/v1/images/?source=/file/v1106978308646140597/products/gtin_8058647620268_01_1500x1500.jpg">
  </div>
</div>

<div class="split right">
  <div class="right_side_list">
  
    <h1>My Journal</h1>

    <%my_notes = current_user.notes%>
    <%my_notes.each do |note|%>
<ul>
    <i class='fas fa-pen-nib'></i><i><%=link_to("#{note.title}", note_path(note))%></i>
</ul>
<%end%>

<div class"new_note">
      <%=link_to("Create a note", new_note_path(@note), method: :get, class: "btn")%>
  </div>
  </div>
</div>

app/views/notes/new.html.erb
<h1>Make a new note.</h1>

<%=render ("form")%>

app/views/notes/show.html.erb
<h1><%=@note.title%></h1>

<p><%=@note.blog%></p>

<img src ="<%=@note.img_url%>">

<%= button_to("Edit this note", edit_note_path(@note), method: :get)%>

<%= button_to("Delete this note.", note_path(@note), method: :delete)%>

<%= button_to("Back to my profile", user_path(session[:user_id]), method: :get) %>

app/views/planets/index.html.erb
<html>
<head>
<title>Title of the document</title>
<style>
body {
  background-image: url(<%= asset_path('stars.jpg') %>);
  background-color: #cccccc;
}

p {
  color: white;
}

h1 {
  color: white;
}
</style>

</head>

<body>
<br></br>
<h1>Popular Destinations</h1>

<br></br>
<!-- list of planets -->
<% @planets.in_groups_of(4, false).each do |group| %>
    <div class='row'>
      <% group.each do |planet| %>
        <div class='col-md-3'>
        <p><%= planet.name %></p>
          <a href="<%= planet_path(planet)%>">
            <img src="<%= planet.planet_img_url %>" class="planet_pic">
            </a>
          </div>
      <% end %>
    </div>
  <% end %>

  </body>
</html>



</body>

</html>

app/views/planets/show.html.erb
<img src = "<%= @planet.img_url%>" class="land_image">
<h1>Planet Name: <i><%=@planet.name%></h1></i>
<p>Terrain: <i><%=@planet.terrain%></p></i>
<p>Temperature: <i><%=@planet.temp_range%></p></i>
<p>Vegetation: <i><%=@planet.vegetation%></p></i> 
<p>Animals: <i><%=@planet.animals%></p></i>
<p>Creatures: <i><%=@planet.local_beings%></p></i>

<br>
<br>
<h1>Planet Reviews</h1>
<%@reviews.each do |review| %>
    <%= link_to("#{review.title}", review_path(review)) %>
    <%end%>

app/views/reservations/index.html.erb
<div class="split left">
  <div class="centered">
    <img src="https://i.pinimg.com/originals/48/83/40/48834011af43753afa57107c67e12dd5.png" width="200" height="600">
  </div>
</div>

<div class="split right">
  <div class="right_side_list">
    <h1>My Reservations</h1>
    <%my_reso = current_user.reservations%>
    <%my_reso.each do |reservation|%>
      <p>Date: <%= link_to("#{reservation.date_time}", reservation_path(reservation))%></p>
        <p>Planet: <%=reservation.planet.name %></p>
        <%= button_to("Delete a reservation", reservation_path(reservation), method: :delete) %>
    <%end%>
  </div>
</div>

app/views/reservations/new.html.erb
    <div class="container">
        <img src="https://i.imgur.com/14mjtNe.jpg"  width="1000" height="300">
        <div class="center"><h1>Book a Reservation</h1></div>
      </div>

      <br>
      <i><p>Reservation time slots are based on peak camping season!</p></i>

    <%= form_for @reservation do |f| %>
        Planet    : <%= f.collection_select(:planet_id, Planet.all, :id, :name)%><br />
        Dates    : <%= f.select :date_time, ['Augyyst 5-10', 'Augyyst 15-20', 'Septzimbaar 5-10', 'Septzimbaar 15-20', 'Uyrkktobar 5-10', 'Uyrkktobar 15-20', 'Knowvrrmbir 5-10', 'Knowvrrmbir 15-20', 'Ten-ymmber 5-10', 'Ten-yember 15-20']%><br />
        Price     : <%= f.select :cost, ['Gold package - 5,000 units', 'Silver package - 2,500 units', 'Bronze package - 1,000 units', 'Roughin it - 50 units'] %><br />
        <br>
    <%= f.submit :Submit, class: 'button' %>
    <% end %>

app/views/reservations/show.html.erb
<h1><%=@reservation.user.name%>'s new reservation</h1>
<img src= "<%=@reservation.planet.img_url%>" class="res_img"><br />
<p>Planet: <%=@reservation.planet.name%></p>
<p>Date: <%=@reservation.date_time%></p>
<p>Cost: <%=@reservation.cost%></p>

app/views/reviews/edit.html.erb
<h3>Edit your Review</h3>
<%= form_for(@review) do |f| %>
        <%= f.label "Review Title" %>
        <%= f.text_field :title %>
        <div>
        <%= f.label :Planet %>
        <%= f.collection_select(:planet_id, Planet.all, :id, :name) %></p>
        <div>
        <%= f.label "Planet Review" %>
        <%= f.text_area :planet_review %>
        <div>
        <%= f.label :Image %>
        <%= f.text_field :img_url %>
        <div>
        <%= f.label "Planet Rating" %>
        <%= f.text_field :rating %>
        <%= f.submit %>
        <%end%>

app/views/reviews/index.html.erb
<h1>All Reviews</h1>

<% @reviews.each do |review| %>
    <p>Planet: <%= review.planet.name %> </p>
   <li><%= link_to(review.title, review_path(review))%></li>
   <%end%>

app/views/reviews/new.html.erb
<h1>Create a review</h1>
<h3>Create a review</h3>
<%= form_for(@review) do |f| %>
        <%= f.label "Review Title" %>
        <%= f.text_field :title %>
        <div>
        <%= f.label :Planet %>
        <%= f.collection_select(:planet_id, Planet.all, :id, :name) %></p>
        <div>
        <%= f.label "Planet Review" %>
        <%= f.text_area :planet_review %>
        <div>
        <%= f.label :Image %>
        <%= f.text_field :img_url %>
        <div>
        <%= f.label "Planet Rating" %>
        <%= f.text_field :rating %>
        <%= f.submit %>
        <%end%>

app/views/reviews/show.html.erb
<h1>Planet Name: <%=@review.planet.name%></h1>
<p>Trip rating: <i><%=@review.rating%></p></i>
<p>Review Title: <i><%=@review.title%></p></i>
<p>User Name: <i><%=@review.user.name%></p></i>
<p>Review: <i><%=@review.planet_review%></p></i>
<br></br>
 <div>   
<h4>Images by <i><%= @review.user.name %></h4></i>
<img src= "<%= @review.img_url %>" id="review_img">
</div>


 <br></br>
 <%= link_to("Delete this review", review_path(@review), method: :delete, class:"btn") %>

app/views/users/edit.html.erb
<h1>Edit your profile </h1>

<%= form_for(@user) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <div>
  <%= f.label :age %>
  <%= f.text_field :age %>
  <div>
  <%= f.label :bio %>
  <%= f.text_area :bio %>
  <div>
  <%= f.label :Image %>
  <%= f.text_field :img_url %>
  <div>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <div>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <div>

  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<%@users.each do |user|%>
<ul>
    <li><%=link_to("#{user.name}", user_path(user))%></li>
</ul>
<%end%>

app/views/users/new.html.erb
<h1>Create a user profile </h1>

<%= form_for(@user) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <div>
  <%= f.label :age %>
  <%= f.text_field :age %>
  <div>
  <%= f.label :bio %>
  <%= f.text_area :bio %>
  <div>
  <%= f.label :Image %>
  <%= f.text_field :img_url %>
  <div>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <div>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <div>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
    <div class="card">
    <br></br>
        <img src="<%= @user.img_url%>" alt="@user.name" style="width:50%" class="prof_img">
<br>
            <h1><i class='fas fa-user-astronaut'></i><%=@user.name%></h1>
                <p><i class='fas fa-birthday-cake'></i><%= @user.age%></p>
                <p class="bio"><%=@user.bio%></p>
            <div style="margin: 50px 0;">

  <p> <%= flash[:info] %></p>

        <%=link_to("Notes", notes_path(current_user), method: :get, class: "btn")%>
        <%=link_to("Reservations", reservations_path(current_user), method: :get, class: "btn")%>
        <%=link_to("Reviews", reviews_path(current_user), method: :get,  class: "btn")%>
        <%=link_to("Logout", logout_path, method: :delete, class: "btn")%>
        <%=link_to("Delete Profile", users_path(current_user), method: :delete, class: "btn")%>
        